name: Build Windows

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller run.py --noconfirm --windowed --name "SublimeScrapperPro"

      - name: Upload Windows App Folder
        uses: actions/upload-artifact@v4
        with:
          name: SublimeScrapperPro-Windows
          path: dist/SublimeScrapperPro
