name: Build and Release

# on:
#   release:
#     types: [created]

on:
    push:
      tags:
        - 'v*'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller run.py --noconfirm --windowed --name "SublimeScrapperPro" --icon=icon.ico

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: SublimeScrapperPro-Windows
          path: dist/SublimeScrapperPro.exe

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt pyinstaller

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Build macOS app
        run: |
          pyinstaller run.py --noconfirm --windowed --name "SublimeScrapperPro" --icon=icon.icns

      - name: Create DMG
        run: |
          create-dmg "dist/SublimeScrapperPro.app" \
            --overwrite \
            --dmg-title="SublimeScrapperPro" \
            --app-drop-link \
            "dist/"

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: SublimeScrapperPro-macOS
          path: dist/SublimeScrapperPro.dmg
